---
server:
  port: 8080

spring:
  application:
    name: template
  webflux:
    base-path: /
  devtools:
    livereload:
      enabled: false
  profiles:
    active: local

logging:
  level:
    co.com.pragma: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
